### ISSUE TITLE
Styles are gone and packages are not listed

### ISSUE THREAD

**Issue by Artalus** [02JanDal/conan_inquiry#10]
Looks almost the same in [Firefox](https://user-images.githubusercontent.com/10381253/50382592-6af79080-06b4-11e9-9187-82b43e6b45dd.png), [Chromium](https://user-images.githubusercontent.com/10381253/50382611-aa25e180-06b4-11e9-825d-83eb3bbe16a9.png) and [Android Chrome](https://user-images.githubusercontent.com/10381253/50382622-07219780-06b5-11e9-80e4-60f186e40dc2.png)

**Comment by Croydon** [comment]
02JanDal seems to not any longer maintaining this project, that's why I did fork this. I would appreciate help. It displays old package data as the automation of this isn't fixed yet

**Comment by Artalus** [comment]
Oh, I did check your fork, but it said the repo was archived, so I thought you are no longer interested in it too. Didn't see there was yet another one :)

https://croydon.github.io/conan_inquiry/ displays same blank slate for me however. I could look into this, but would appreciate any hints on where to look.

**Comment by Croydon** [comment]
Oops, thanks for the heads up. Seems to be broken just recently. My web console outputs warnings about cross origin request while loading the external JavaScript libs and also errors that the sha256 hashes are wrong in the `integrity` attribute. Which is quite odd as these definitely should suddenly change...

**Comment by Croydon** [comment]
https://github.com/cdnjs/cdnjs/issues/13165

**Comment by Croydon** [comment]
Fixed upstream.

**Comment by Artalus** [comment]
Yup, works in both your and 02JanDal's repos
